# macos-build.yml (수정본 - 핵심 부분만)
steps:
- uses: actions/checkout@v4

- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.11'

# ── 여기! Homebrew 로 설치 ─────────────────────────────
- name: Install create-dmg
  run: brew install create-dmg
# ──────────────────────────────────────────────────────

- name: Install Python deps
  run: |
    python -m pip install -r requirements.txt
    python -m pip install pyinstaller==6.14.1

- name: Build app
  run: |
    pyinstaller run_app.py \
      --name DJToolkit \
      --windowed \
      --add-data "home.py:." \
      --add-data "pages:pages" \
      --add-data ".streamlit:.streamlit" \
      --collect-all streamlit \
      --collect-all librosa \
      --collect-all mutagen \
      --collect-submodules soundfile

- name: Create DMG
  run: |
    create-dmg dist/DJToolkit.app --overwrite
    mv DJToolkit-*.dmg DJToolkit_mac.dmg

- uses: actions/upload-artifact@v4
  with:
    name: DJToolkit_mac.dmg
    path: DJToolkit_mac.dmg
