# .github/workflows/macos-build.yml
name: Build macOS DMG

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    # 1. 소스 체크아웃
    - uses: actions/checkout@v4

    # 2. Python 3.11
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # 3. PyInstaller & dmgbuild 설치
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pyinstaller==6.14.1 dmgbuild

    # 4. .app 번들 만들기
    - name: Build .app bundle
      run: |
        pyinstaller run_app.py \
          --name DJToolkit \
          --windowed \
          --add-data "home.py:." \
          --add-data "pages:pages" \
          --add-data ".streamlit:.streamlit" \
          --collect-all streamlit \
          --collect-all librosa \
          --collect-all mutagen \
          --collect-submodules soundfile

    # 5-A. dmgbuild 설정 파일 작성
    - name: Generate dmgbuild settings
      run: |
        cat <<'PY' > settings.py
        files = [app]          # DMG에 포함될 항목
        dmg_properties = {
            'volume-name': 'DJToolkit',
        }
        PY

    # 5-B. DMG 생성
    - name: Create DMG
      run: |
        dmgbuild -s settings.py -D app=dist/DJToolkit.app \
                 "DJToolkit" DJToolkit_mac.dmg

    # 6. 결과 DMG 업로드
    - uses: actions/upload-artifact@v4
      with:
        name: DJToolkit_mac.dmg
        path: DJToolkit_mac.dmg
